### ISSUE TITLE
Long names are not properly scaled down for some templates

### ISSUE THREAD

**Issue by jtkimbell** [mgula57/mlb_showdown_card_bot#44]
For very long names, like Jarrod Saltalamacchia, they are cut off on the front and/or end of the name.

You can repro with Jarrod Saltalamacchia, year 2014, and card style 2000, 2002, 2004, and 2005.

![image](https://user-images.githubusercontent.com/44843397/103719665-5a09d700-4f7e-11eb-8c41-f7d91622a376.png)
![image](https://user-images.githubusercontent.com/44843397/103719698-6c841080-4f7e-11eb-87ba-ec471e20a110.png)

**Comment by mgula57** [comment]
Fixed in release 1.5
