### ISSUE TITLE
Cannot generate cards via -show on Windows 10

### ISSUE THREAD

**Issue by jtkimbell** [mgula57/mlb_showdown_card_bot#45]
On Windows 10, running showdownbot with the '-show' flag results in an errno22 100% of the time.

> OSError: [Errno 22] Invalid argument: 'c:\\users\\jt.000\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\mlb_showdown_bot\\output\\Jeremy Hellickson-2021-01-04 21:55:34.944513.png'

Funny enough, if I comment out line #1449, the image will be generated.
`player_image.save(os.path.join(os.path.dirname(__file__), 'output', self.image_name), dpi=(300, 300), quality=100)`

However, that is a hacky solution, as it generates the image, then immediately deletes it from the temp directory. So I have no copy of the image outside of what was opened in the system image viewer. So the image is being generated correctly, but not saved properly.

**Comment by mgula57** [comment]
@jtkimbell Can you upgrade to v1.5 and see if this is still an issue? Also what version of python are you using?

**Comment by jtkimbell** [comment]
Thanks @mgula57 

Python is 3.9.1.

I just upgraded to ShowdownBot 1.5.1. Still the same error, here's the full output. I haven't tried commenting out that line as a workaround yet tonight.

`C:\Users\JT.000>showdownbot -n "Jeremy Hellickson" -y 2010 -url http://images.pe
rformgroup.com/di/library/omnisport/f0/6d/hellickson-jeremy-usnews-060318-ftr-ge
tty_fovffc2jz3ja10yjtab2t4v0h.jpg?t=-961957021 -show
***********************************************
Jeremy Hellickson (2010) (TBR)
2000 Base Set Card

RELIEVER
RHP
4 IP

260 PT.
OBP:66  BA:32  SLG:40  SPD/IP:120

CONTROL: 4
SO: 1-5
PU: 6-7
GB: 8-12
FB: 13-17
BB: -
1B: 18-19
2B: 20
HR: -


Statline

Showdown            Real
----------     ---------
 BA: .242       BA: .232
OBP: .278      OBP: .282
SLG: .376      SLG: .384

 PA: 149        PA:  149
 1B: 22         1B:   21
 2B: 8          2B:    6
 3B: 0          3B:    0
 HR: 2          HR:    5
 BB: 7          BB:    8
 SO: 31         SO:   33

***********************************************
Traceback (most recent call last):
  File "c:\users\jt.000\appdata\local\programs\python\python39\lib\runpy.py", li
ne 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jt.000\appdata\local\programs\python\python39\lib\runpy.py", li
ne 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\JT.000\AppData\Local\Programs\Python\Python39\Scripts\showdownb
ot.exe\__main__.py", line 7, in <module>
  File "c:\users\jt.000\appdata\local\programs\python\python39\lib\site-packages
\mlb_showdown_bot\__main__.py", line 36, in main
    showdown = ShowdownPlayerCardGenerator(
  File "c:\users\jt.000\appdata\local\programs\python\python39\lib\site-packages
\mlb_showdown_bot\showdown_player_card_generator.py", line 73, in __init__
    self.player_image(show=True)
  File "c:\users\jt.000\appdata\local\programs\python\python39\lib\site-packages
\mlb_showdown_bot\showdown_player_card_generator.py", line 1580, in player_image

    player_image.save(os.path.join(os.path.dirname(__file__), 'output', self.ima
ge_name), dpi=(300, 300), quality=100)
  File "c:\users\jt.000\appdata\local\programs\python\python39\lib\site-packages
\PIL\Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'c:\\users\\jt.000\\appdata\\local\\progra
ms\\python\\python39\\lib\\site-packages\\mlb_showdown_bot\\output\\Jeremy Helli
ckson-2021-01-18 18:03:24.922860.png'`

**Comment by jtkimbell** [comment]
And I verified that commenting out line 1580 in showdown_player_card_generator.py "fixes" the issue.

`player_image.save(os.path.join(os.path.dirname(__file__),` 'output', self.image_name), dpi=(300, 300), quality=100)

It pops up the image, but of course it doesn't save it anywhere because I've commented out that line.

**Comment by jtkimbell** [comment]
I think I figured it out! It's an issue with the timestamp. 

Today, you have this line (around 1576, though it may have changed as I added test lines and comments throughout the code):
`self.image_name = '{name}-{timestamp}.png'.format(name=self.name, timestamp=str(datetime.now()))`

If I replace it with this line, it all works successfully:
`self.image_name = '{name}-{timestamp}.png'.format(name=self.name, timestamp=str(datetime.now().date()))`

So I wondered if it was an issue with the spaces. So I stripped them with replace(" ", ""). That didn't work. So then I wondered if it was the colon. So I did this: replace(":", "_"). It worked!

`self.image_name = '{name}-{timestamp}.png'.format(name=self.name, timestamp=str(datetime.now())).replace(":", "_")`

**Comment by jtkimbell** [comment]
New issue - the cards only save to the output directory if I have the -show flag. Otherwise they do not save. I haven't figured this one out yet.

**Comment by jtkimbell** [comment]
Sorry for the third post, but I figured it out. Unless -show is passed, the player_image() function will never be called. So I added an else statement in init.

`        if show_player_card_image:
            self.player_image(show=True)
        else:
            self.player_image(show=False)`

**Comment by mgula57** [comment]
@jtkimbell Apologies for the late response on this thread. Glad you were able to figure this out. The behavior of not generating the player image by default is intentional. I should however have a separate input that has the bot just generate the image without showing it

**Comment by mgula57** [comment]
Closing this issue, fixed with subsequent releases
